### PR TITLE
fixed __attributes __format__

### PR DESCRIPTION
**Pull request by Moonixp**
changed the directory for source files

added shared files

Updated readme

moved binary to bin/binary

### CODE REVIEW

**Review by Moonixp — COMMENTED** [review]
looks okay

**Review by punixcorn — APPROVED** [review]
make fails to bin folder  not existing

**Review by punixcorn — CHANGES_REQUESTED** [review]
fix Makefile dirs and add a make_check for new workflow

**Review by Moonixp — COMMENTED** [review]
changes made

**Comment by punixcorn** [comment]
still fails but works, put the checks on bin folder in scripts

**Pull request merged**
